src/views/Tools/components/WebSocketItem.vue

fix(websocket): add retain column

---

src/hooks/useDatabaseConfig.js
src/i18n/Auth.js
src/views/Auth/AuthnCreate.vue
src/views/Auth/components/DatabaseConfig.vue
src/views/Auth/style/auth.scss
vue.config.js

feat(authn): complete the redis config page

---

script/config.json
src/routes/index.js
vue.config.js

Reverts emqx/emqx-dashboard-web#331

Revert "feat(config.json): reset public path(card 1214 in jira)"

---

package.json
script/config.json

add additional command for cloud CI build emqx dashboard

refactor(cloud): change cloud build config

---

src/views/RuleEngine/components/RuleActions.vue

https://emqx.atlassian.net/browse/ED-824

style(rule): solve the issue of overflow

---

src/components/FileEditor.vue

https://emqx.atlassian.net/browse/ED-825

fix(file editor): add default value

---

src/i18n/Clients.js
src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-961

feat(client): supported exactly match client id

---

src/i18n/Clients.js
src/views/Clients/Clients.vue

https://emqx.atlassian.net/browse/ED-961

refactor(client): styles for exact searches

---

src/api/rules.js
src/views/RuleEngine/components/ResourceNode.vue

https://emqx.atlassian.net/browse/ED-969

refactor(resource): add node params when reconnect a specific node

---

src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-997

fix(user): tags is not required field

---

src/components/CustomNumberInput.vue
src/views/Settings/components/ConfigDetail.vue

https://emqx.atlassian.net/browse/ED-978

fix(setting): use number input

---

src/views/Settings/components/ConfigDetail.vue

https://emqx.atlassian.net/browse/ED-1007

fix(conf): can not update internal zone

---

src/stores/index.js
src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1007

fix(user): update role after updating user

---

src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1012

fix(user): viewer should be able to change self pwd

---

src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1004

fix(user): judgment logic for whether to display the delete button

---

src/i18n/Modules.js

https://emqx.atlassian.net/browse/ED-1006
the last one

fix(log): change `source` to `user/appid`

---

src/assets/style/common.scss
src/views/Clients/ClientDetails.vue

https://emqx.atlassian.net/browse/ED-1013

fix(client): styling issues when username and id are too long

---

src/common/utils.js
src/components/CustomNumberInput.vue

https://emqx.atlassian.net/browse/ED-1015

fix(setting): add min value limit for numeric conf items

---

src/views/RuleEngine/components/RuleActions.vue

https://emqx.atlassian.net/browse/EMQX-11204

fix(rule): desc of action disapear after refreshing metrics

---

src/views/General/Users.vue

https://emqx.atlassian.net/browse/ED-1012
refix..

fix(user): just request change pwd when user is viewer

---

src/views/General/Log.vue
src/views/General/resource_dict.json

https://emqx.atlassian.net/browse/EMQX-11237

fix(audit): fixed typo

---

src/views/Settings/ListenerSettings.vue

https://emqx.atlassian.net/browse/ED-1010

fix(setting): do not pop up confirm after deleting

---

src/api/common.js
src/api/rules.js

https://emqx.atlassian.net/browse/ED-1132

fix(rule): problem of data errors when adding float

---

src/api/logTrace.js
src/common/http.js

https://emqx.atlassian.net/browse/ED-1275

fix(log trace): alert content when log trace does not exist

---

src/views/Modules/components/AuthMnesia/AclTablePage.vue
src/views/Modules/components/AuthMnesia/AuthTablePage.vue

https://emqx.atlassian.net/browse/ED-1262

fix(module): problem of pagination in auth

---

src/views/RuleEngine/Rules.vue

https://emqx.atlassian.net/browse/ED-1326

fix(rule): data wrong after filter table data

---

src/views/General/resource_dict.json

https://emqx.atlassian.net/browse/ED-1333

fix(audit log): fix two English

---

src/views/Modules/ModuleDetail.vue

https://emqx.atlassian.net/browse/ED-1338

fix(module): module details configuration form value error

---

src/assets/style/common.scss
src/components/LeftBar.vue

https://emqx.atlassian.net/browse/ED-1441
https://emqx.atlassian.net/browse/ED-1336

style(left menu): styling issues when expanding

---

src/api/backup.js
src/views/General/Backup.vue

https://emqx.atlassian.net/browse/ED-1472

fix(backup): setting a larger timeout for restore backups

---

src/views/General/LogTrace.vue
src/views/Modules/ModuleDetail.vue
src/views/Modules/components/LogTrace/LogContent.vue

https://emqx.atlassian.net/browse/ED-1533

refactor(module): add back log trace table

---

src/views/Modules/components/UsernameQuota/UsernameQuota.vue

https://emqx.atlassian.net/browse/ED-1595
https://emqx.atlassian.net/browse/ED-1593

fix(modules): placeholder in input and data count

---

src/views/Modules/components/UsernameQuota/UsernameQuota.vue

fix(modules): sessions, not connections

---

.github/workflows/build_packages.yaml
src/views/Settings/ClusterSettings.vue

https://emqx.atlassian.net/browse/ED-1645

fix(settings): incorrect status of nodes in cluster

---

src/api/cluster.js
src/views/Settings/ClusterSettings.vue

https://emqx.atlassian.net/browse/ED-1675

fix(cluster settings): correct node list
